language: node_js
node_js:
  - "8.10"
install: true
script: skip
before_deploy: cd lambda/events_id/delete
deploy:
    - provider: lambda
      role: $AWS_LAMBDA_ROLE_ARN_PROD
      zip: delete.zip
      function_name: "ak-events_id-delete-lambda"
      region: "us-west-2"
      handler_name: "handler"
      runtime: "nodejs8.10"
      on:
        branch: 
        - travis-feature/deleteLambda
