--- 
branch: dev
branches: 
  only: 
    - dev
    - prod
install: 
  - "npm install npm@latest -g"
  - "npm install aws-sdk"
jobs: 
  - 
    deploy: ~
    function_name: ak-api-alex-lambda
    handler_name: handler
    provider: lambda
    region: us-east-2
    role: $AWS_LAMBDA_ROLE_ARN
    runtime: nodejs8.10
    script: "npm test lambda/post.js"
    stage: "deploy post.js to dev env"
    true: 
      branch: dev
  - 
    deploy: ~
    function_name: ak-api-jonathan-lambda
    handler_name: handler
    provider: lambda
    region: us-east-2
    role: $AWS_LAMBDA_ROLE_ARN
    runtime: nodejs8.10
    script: "npm test lambda/ping.js"
    stage: "deploy ping.js to dev env"
    true: 
      branch: dev
  - 
    deploy: ~
    function_name: ak-api-travis-lambda
    handler_name: handler
    provider: lambda
    region: us-east-2
    role: $AWS_LAMBDA_ROLE_ARN
    runtime: nodejs8.10
    script: "npm test sprint3/events/index.js"
    stage: "deploy index.js to dev env"
    true: 
      branch: dev
  - 
    deploy: ~
    function_name: ak-api-zach-lambda
    handler_name: handler
    provider: lambda
    region: us-east-2
    role: $AWS_LAMBDA_ROLE_ARN
    runtime: nodejs8.10
    script: "npm test api/lambda/getEventById/index.js"
    stage: "deploy index.js(zach) to dev env"
    true: ~
language: node_js
node_js: 
  - "8.10"
