language: node_js
node_js:
  - "8.10"
install: true
script: skip
before_deploy: cd lambda
deploy:
    provider: lambda
    role: $AWS_LAMBDA_ROLE_ARN
    function_name: "ak-api-dev-lambda"
    region: "us-east-2"
    handler_name: "handler"
    runtime: "nodejs8.10"
    on:
      branch: 
      - dev
