language: node_js
node_js:
  - "8.10"
install:
  - npm install npm@latest -g
  - npm install aws-sdk
branches:
  only: 
  - dev
  - prod
jobs:
  include:
  - stage: deploy post.js to dev env
    script: npm test lambda/post.js
