language: node_js
node_js:
  - "8.10"
install:
  - npm install npm@latest -g
  - npm install aws-sdk
branches:
  only: 
  - dev
  - prod
jobs:
  include:
  - stage: deploy post.js to dev env
    script: npm test lambda/post.js
  - stage: deploy ping.js to dev env
    script: npm test lambda/ping.js
  - stage: deploy index.js to dev env
    script: npm test sprint3/events/index.js
  - stage: deploy index.js(zach) to dev env
    script: npm test api/lambda/getEventById/index.js
