language: node_js
node_js:
  - "8.10"
install:
  - npm install npm@latest -g
  - npm install aws-sdk
branches:
  only: 
  - dev
  - prod
jobs:
  include:
  - stage: deploy post.js to dev env
    script: npm test lambda/post.js
    deploy:
    provider: lambda
    role: $AWS_LAMBDA_ROLE_ARN
    function_name: "ak-api-alex-lambda"
    region: "us-east-2"
    handler_name: "handler"
    runtime: "nodejs8.10"
    on:
      branch: dev
